In [2]:
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline
import pandas
from sklearn.model_selection import train_test_split
import numpy as np

In [4]:
file_location = "../../data/Tweets.csv"
tweets = pandas.read_csv(file_location)
tweets.head()

FileNotFoundError: [Errno 2] File ../../data/Tweets.csv does not exist: '../../data/Tweets.csv'

In [162]:
tweets_mod = tweets[["airline_sentiment","airline","text"]]

In [163]:
tweets_mod['airline'].value_counts()

United            3822
US Airways        2913
American          2759
Southwest         2420
Delta             2222
Virgin America     504
Name: airline, dtype: int64

In [164]:
tweets_mod.head()

airline_sentiment         airline  \
0           neutral  Virgin America   
1          positive  Virgin America   
2           neutral  Virgin America   
3          negative  Virgin America   
4          negative  Virgin America   

                                                text  
0                @VirginAmerica What @dhepburn said.  
1  @VirginAmerica plus you've added commercials t...  
2  @VirginAmerica I didn't today... Must mean I n...  
3  @VirginAmerica it's really aggressive to blast...  
4  @VirginAmerica and it's a really big bad thing...

In [154]:
tweets_mod["text"].str.lower() 

0                      @virginamerica what @dhepburn said.
1        @virginamerica plus you've added commercials t...
2        @virginamerica i didn't today... must mean i n...
3        @virginamerica it's really aggressive to blast...
4        @virginamerica and it's a really big bad thing...
                               ...                        
14635    @americanair thank you we got on a different f...
14636    @americanair leaving over 20 minutes late flig...
14637    @americanair please bring american airlines to...
14638    @americanair you have my money, you change my ...
14639    @americanair we have 8 ppl so we need 2 know h...
Name: text, Length: 14640, dtype: object

In [155]:
tweets_mod.head()
tweets_mod.shape

(14640, 3)

In [ ]:
tweets_mod.isnull().sum()

In [159]:
tweets_mod.replace('', np.nan)

airline_sentiment         airline  \
0               neutral  Virgin America   
1              positive  Virgin America   
2               neutral  Virgin America   
3              negative  Virgin America   
4              negative  Virgin America   
...                 ...             ...   
14635          positive        American   
14636          negative        American   
14637           neutral        American   
14638          negative        American   
14639           neutral        American   

                                                    text  
0                    @VirginAmerica What @dhepburn said.  
1      @VirginAmerica plus you've added commercials t...  
2      @VirginAmerica I didn't today... Must mean I n...  
3      @VirginAmerica it's really aggressive to blast...  
4      @VirginAmerica and it's a really big bad thing...  
...                                                  ...  
14635  @AmericanAir thank you we got on a different f...  
14636  @AmericanAir leaving over 20 minutes Late Flig...  
14637  @AmericanAir Please bring American Airlines to...  
14638  @AmericanAir you have my money, you change my ...  
14639  @AmericanAir we have 8 ppl so we need 2 know h...  

[14640 rows x 3 columns]

In [160]:
tweets_mod.dropna()

airline_sentiment         airline  \
0               neutral  Virgin America   
1              positive  Virgin America   
2               neutral  Virgin America   
3              negative  Virgin America   
4              negative  Virgin America   
...                 ...             ...   
14635          positive        American   
14636          negative        American   
14637           neutral        American   
14638          negative        American   
14639           neutral        American   

                                                    text  
0                    @VirginAmerica What @dhepburn said.  
1      @VirginAmerica plus you've added commercials t...  
2      @VirginAmerica I didn't today... Must mean I n...  
3      @VirginAmerica it's really aggressive to blast...  
4      @VirginAmerica and it's a really big bad thing...  
...                                                  ...  
14635  @AmericanAir thank you we got on a different f...  
14636  @AmericanAir leaving over 20 minutes Late Flig...  
14637  @AmericanAir Please bring American Airlines to...  
14638  @AmericanAir you have my money, you change my ...  
14639  @AmericanAir we have 8 ppl so we need 2 know h...  

[14640 rows x 3 columns]

In [126]:
tweets_mod.isnull().sum()

airline_sentiment    0
airline              0
text                 0
dtype: int64

In [140]:
from sklearn.feature_extraction.text import CountVectorizer

# This converts the list of words into space-separated strings
#tweets_mod['text'].apply(lambda x: ' '.join(x))

In [141]:
count_vect = CountVectorizer()
counts = count_vect.fit_transform(tweets_mod['text'])

In [142]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer().fit(counts)

counts = transformer.transform(counts)  

In [143]:
counts

<14640x15051 sparse matrix of type '<class 'numpy.float64'>'
	with 234281 stored elements in Compressed Sparse Row format>

In [144]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [145]:
le.fit(tweets_mod['airline'])

LabelEncoder()

In [146]:
tweets_mod

airline_sentiment         airline  \
0               neutral  Virgin America   
1              positive  Virgin America   
2               neutral  Virgin America   
3              negative  Virgin America   
4              negative  Virgin America   
...                 ...             ...   
14635          positive        American   
14636          negative        American   
14637           neutral        American   
14638          negative        American   
14639           neutral        American   

                                                    text  
0                    @VirginAmerica What @dhepburn said.  
1      @VirginAmerica plus you've added commercials t...  
2      @VirginAmerica I didn't today... Must mean I n...  
3      @VirginAmerica it's really aggressive to blast...  
4      @VirginAmerica and it's a really big bad thing...  
...                                                  ...  
14635  @AmericanAir thank you we got on a different f...  
14636  @AmericanAir leaving over 20 minutes Late Flig...  
14637  @AmericanAir Please bring American Airlines to...  
14638  @AmericanAir you have my money, you change my ...  
14639  @AmericanAir we have 8 ppl so we need 2 know h...  

[14640 rows x 3 columns]

In [147]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(counts, tweets_mod['airline'], test_size=0.1)

In [165]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train, y_train)  

In [166]:
import numpy as np

predicted = model.predict(X_test)

print(np.mean(predicted == y_test))  

from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, predicted))

0.7281420765027322
[[183   1   0  33  66   0]
 [ 13 127   1  10  72   0]
 [ 10   1 161  17  73   0]
 [ 11   0   1 249  41   0]
 [  3   0   1   3 343   0]
 [  1   1   4   4  31   3]]


In [167]:
model = MultinomialNB(alpha=0.5).fit(X_train, y_train)
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))

0.7281420765027322
[[183   1   0  33  66   0]
 [ 13 127   1  10  72   0]
 [ 10   1 161  17  73   0]
 [ 11   0   1 249  41   0]
 [  3   0   1   3 343   0]
 [  1   1   4   4  31   3]]


In [168]:
model = MultinomialNB(alpha=0.8).fit(X_train, y_train)
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))

0.7049180327868853
[[175   1   0  25  82   0]
 [ 10 116   1   7  89   0]
 [ 10   1 146  12  93   0]
 [  5   0   0 246  51   0]
 [  1   0   0   0 349   0]
 [  1   0   4   3  36   0]]


In [169]:
model = MultinomialNB(alpha=0.6).fit(X_train, y_train)
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))

0.7213114754098361
[[182   1   0  31  69   0]
 [ 12 122   1  10  78   0]
 [ 10   1 157  18  76   0]
 [  5   0   0 250  47   0]
 [  3   0   1   2 344   0]
 [  1   1   4   3  34   1]]


In [170]:
model = MultinomialNB(alpha=0.55).fit(X_train, y_train)
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))

0.7254098360655737
[[180   1   0  33  69   0]
 [ 12 127   1  10  73   0]
 [ 10   1 161  16  74   0]
 [  8   0   1 248  45   0]
 [  3   0   1   2 344   0]
 [  1   1   4   3  33   2]]


In [172]:
model = MultinomialNB(alpha=0.54).fit(X_train, y_train)
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))

0.7254098360655737
[[181   1   0  34  67   0]
 [ 12 127   1  10  73   0]
 [ 10   1 161  16  74   0]
 [  9   0   1 247  45   0]
 [  3   0   1   3 343   0]
 [  1   1   4   3  32   3]]
